import Head from 'next/head'
import { Roboto } from '@next/font/google'
import styles from '@/styles/Header.module.css'
import AuthContext from '../context/AuthContext'
import { useState, useEffect, useContext } from 'react'
import "../flow/config";
import * as fcl from "@onflow/fcl";
const roboto = Roboto({ weight: '500', subsets: ['latin'] })
import Link from 'next/link'

export default function Header() {
  // const [flowUser, setFlowUser] = useState({ loggedIn: null, addr: null })
  const { user, login, register, logout, checkUserLoggedIn } = useContext(AuthContext);
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const AuthedState = () => {
    return (
      <nav className={`bg-slate-700 ${styles.navbar}`}>
        <div class="container flex flex-wrap items-center justify-between mx-auto">
          <Link href="/" className={styles.brand}>Flower Ronin</Link>
          <button onClick={toggleMenu} data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
          </button>
          {isMenuOpen ? (
            <div className={`${
              isMenuOpen ? '' : 'hidden'
            }   w-full lg:inline-flex lg:flex-grow lg:w-auto`} id="navbar-default">
              <ul className="flex flex-col w-full bg-slate-500 p-4 mt-2 absolute right-0">
                <li>
                  <Link href="/" className="mr-3">Home</Link>
                </li>
                <li>
                  <Link href="/dashboard" className="mr-3">Dashboard</Link>
                </li>
                <li>
                  <Link href="/inbox" className="mr-3">Inbox</Link>
                </li>
                <li>
                  <button onClick={fcl.unauthenticate}>Log Out</button>
                </li>
              </ul>
            </div>
          ) : (
            <div className="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul className="flex flex-row">
                <li>
                  <Link href="/" className="mr-4">Home</Link>
                </li>
                <li>
                  <Link href="/dashboard" className="mr-4">Dashboard</Link>
                </li>
                <li>
                  <Link href="/inbox" className="mr-4">Inbox</Link>
                </li>
                <li>
                  <button onClick={fcl.unauthenticate}>Log Out</button>
                </li>
              </ul>
            </div>
          )}
        </div>
      </nav>
    )
  }

  const UnauthenticatedState = () => {
    return (
      <div className={`bg-slate-700 ${styles.navbar}`}>
        <div className={styles.brand}>Flower Ronin</div>
        <Link href="/login">Login</Link>
      </div>
    )
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={roboto.className}>
        {user?.loggedIn
          ? <AuthedState />
          : <UnauthenticatedState />
        }
      </div>
    </>
  )
}