import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import AuthContext from '../context/AuthContext'
import { useState, useEffect, useContext } from 'react'
import "../flow/config";
import * as fcl from "@onflow/fcl";
import Layout from '../components/Layout'
import Link from 'next/link'

export default function About() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>About</h1>
        <p>Have you ever wanted to reach out to another wallet but was not able to find their contact info or able to reach them whether you wanted to compliment their collection or inquire about an offer of a piece in their collection?</p>
        <p>It is currently hard to be able to send those a message. We created this app to help solve that problem. You can send messages to another wallet here, create a profile to share your info if you would like and also even post listings. You can enage with the community as well.</p>
        <p>Another part of the problem is that even if you do send a message, there would not be a guarentee that they saw the message.</p>
        <p>That is where a utility coin comes in where we reward users that use our application with these tokens.</p>
        <p>These tokens can be used to be able to edit a banner on the dashboard that all the users will see. People can collect more coins from other users to be able to have their banner on the dashboard more often. </p>
      </Layout>
    </>
  )
}